Translations update from Weblate
seedvault-app/seedvault pull request #187
Opened 2021-01-06 00:29 UTC by weblate

Translations update from [Weblate](https://hosted.weblate.org/projects/calyxos/seedvault/) for CalyxOS/Seedvault.

Current translation status:

![Weblate translation status](https://hosted.weblate.org/widgets/calyxos/-/seedvault/horizontal-auto.svg)

2021-04-16 18:00 UTC, chirayudesai commented
@mikeNG Did we decide on just translating / merged into android11?

That'd make master behind android11, not fun.

2021-04-19 21:35 UTC, mikeNG commented
> @mikeNG Did we decide on just translating / merged into android11?
> 
> That'd make master behind android11, not fun.

That's the only way to get correct translations for android11 when using weblate (only supports one branch), since there might be new/changed/removed strings in master branch that are not in android11

2021-04-19 22:33 UTC, chirayudesai requested changes
In that case, let's merge this.

I commented on the strings the CI blew up on, haven't looked at the others.

2021-04-19 22:33 UTC, chirayudesai commented on app/src/main/res/values-my/strings.xml
> +    <string name="notification_success_text">အပ်ပလီကေးရှင်းများကူးထားပြီပါပြီ</string>
values-my/strings.xml:7: This definition does not require arguments

2021-04-19 22:33 UTC, chirayudesai commented on app/src/main/res/values-my/strings.xml
> +    <string name="recovery_code_error_invalid_word">စကားလုံးမှားယွင်းနေပါသည်။</string>
values-my/strings.xml:13: This definition does not require arguments

2021-04-19 22:33 UTC, chirayudesai commented on app/src/main/res/values-my/strings.xml
> +    <string name="settings_auto_restore_summary_usb">သင်၏% 1 $ s ကိုဤအလုပ်မလုပ်ရန်ချိတ်ဆက်ရန်လိုအပ်သည်.</string>
values-my/strings.xml:61: This definition does not require arguments

2021-07-05 12:43 UTC, chirayudesai approved these changes
Did some minor fixes in local commits.

2021-07-05 12:43 UTC, merged