Improve recovery code output fragment's wordlist layout
seedvault-app/seedvault pull request #236
Opened 2021-04-09 22:23 UTC by luk1337

* Enable scrollbar
* Enable text size autoscalling (min 12sp, max 24sp)
* Fix wordList constraints
* Set wordList height to match_parent so that scrollbar
  our word list will always start from top
* Set wordList width to match_parent so that scrollbar
  is displayed on the sides
* Reduce landscape spanCount to 3 so that we'll be less
  likely to clip the some longer word

Change-Id: I7a2481fe25163f81f6d3c3626784cc4681f7c4ef

2021-04-09 22:24 UTC, luk1337 commented
Mostly affects 16:9 devices with display size / font-size set to high values.

2021-04-12 18:41 UTC, grote approved these changes
I didn't run this code, but assume @luk1337 did that. The changes look ok.

2021-04-12 19:16 UTC, luk1337 commented
@grote yeah, it'd be hard to do that kind of stuff blind.

2021-04-16 17:54 UTC, chirayudesai commented
This makes it look really small on bigger devices now.

![Screenshot_20210416-232344](https://user-images.githubusercontent.com/952062/115064688-d8293280-9f0a-11eb-8212-525b12f45ea4.png)

That's bramble, 1080x2340, 420dpi. It would fill the whole screen nicely before, now the text is way too small.

2021-04-16 17:56 UTC, chirayudesai requested changes
Should ideally stay as close to before as possible on other devices.

2021-04-16 17:58 UTC, luk1337 commented
Try removing android:autoSize{Min,Max}TextSize and testing it on different DPIs.

2021-04-16 18:09 UTC, chirayudesai commented
> Try removing android:autoSize{Min,Max}TextSize and testing it on different DPIs. Everything else should be ok

Now it looks ok, but cuts off words on larger/largest densities.

2021-04-16 19:36 UTC, chirayudesai approved these changes
Works much better, thanks!

2021-04-19 18:46 UTC, grote requested changes
To be honest, I am not happy with the hardcoding of the list item height and some other changes. I pushed an alternative solution to https://github.com/grote/seedvault/tree/recovery-code-output-small-screens

2021-07-05 13:27 UTC, chirayudesai commented
Merged https://github.com/seedvault-app/seedvault/pull/276 instead.

Makes it look slightly different on all devices, and a lot better on smaller screens / larger dpis.

![image](https://user-images.githubusercontent.com/952062/124478411-c85f1300-ddc2-11eb-8923-f9738e1d2325.png)

This has a scrollbar, compared to cutoff text and no scrolling before.

2021-07-05 13:27 UTC, closed without merging