Restrict exported components
seedvault-app/seedvault pull request #287
Opened 2021-07-18 01:30 UTC by flawedworld

2021-08-11 08:02 UTC, grote commented
@flawedworld thanks for the PR!

Do you mind adding a bit of explanation for the benefit of restricting opening those activities? Maybe also compared to the downsides of not being able to open restore activity with adb anymore?

2021-08-20 02:43 UTC, flawedworld commented
Exported components should pretty much always be restricted. It's a best practice (see CWE-926). Other applications not within the scope of ```system|signature``` should never be able to open those activities because they do not need to. Using ADB to open activities should never be done outside of a debug environment.

2021-08-25 12:54 UTC, mikeNG requested changes

2021-08-25 12:54 UTC, mikeNG commented on app/src/main/AndroidManifest.xml
> +        android:name="com.stevesoltys.seedvault.opensettings"
I would suggest changing this to "com.stevesoltys.seedvault.OPEN_SETTINGS", following AOSP permission naming

2021-08-25 12:54 UTC, mikeNG commented on app/src/main/AndroidManifest.xml
> +        android:name="com.stevesoltys.seedvault.restorebackup"
Same for this, "com.stevesoltys.seedvault.RESTORE_BACKUP"

2021-09-28 16:21 UTC, chirayudesai commented
Thanks for the PR.

By default, the 'restore option' in menu isn't enabled since restoring backups to an existing system may cause some weirdness.

adb was one way around that, but not ideal.

We should add some other way to getting to the restore menu on-device, a `*#*#RESTORE#*#*` `SECRET_CODE` would work.

Although that can be done separate from this PR.

2021-09-29 13:27 UTC, chirayudesai commented
Rolled into https://github.com/seedvault-app/seedvault/pull/319 after resolving merge conflict.

2021-09-29 13:27 UTC, closed without merging