Disable Nextcloud restore when not installed and no store available
seedvault-app/seedvault pull request #302
Opened 2021-08-25 13:09 UTC by mikeNG

Attempting to install Nextcloud in SetupWizard on a device
that has no app store installed results in a crash.
Disable the option and use an appropriate summary.

Change-Id: Ie3dff8d85ed68b27858fa37b3efb97eb345fa372

2021-08-25 13:17 UTC, grote requested changes

2021-08-25 13:17 UTC, grote commented on app/src/main/java/com/stevesoltys/seedvault/ui/storage/StorageRootFetcher.kt
> +            else R.string.storage_fake_nextcloud_summary
Nitpick: I'd switch the logic here and don't negate `canInstall`.

2021-08-25 13:17 UTC, grote commented on app/src/main/java/com/stevesoltys/seedvault/ui/storage/StorageRootFetcher.kt
> +            enabled = (!isInstalled && canInstall) || (isRestore && (!isInstalled && canInstall)),
Can we maybe simplify this logic here? Would `isInstalled || canInstall` work as well? Just judging from the click listener here.

2021-09-23 21:23 UTC, chirayudesai approved these changes
Works with a store installed as well.

2021-09-23 21:23 UTC, merged